#!/usr/bin/env pwsh
# SPDX-License-Identifier: GPL-3.0-only
#
# MuseScore fork CI: Windows application package helper.
#
# Turns an installed MuseScore tree (cmake --install output) into exactly one
# unsigned, extract-and-run ZIP plus external SHA256SUMS.txt and
# build-manifest.json.
#
# Format contract:
#   * ZIP archive. This is NOT an installer, NOT an MSI and NOT the PortableApps
#     build. It is an ordinary application archive: extract and run bin/MuseScoreStudio5.exe.
#   * The install tree is never renamed and never mutated. A separate staging
#     copy is not used; the archive is read directly from the install directory.
#   * build.release / any build tree is never packaged.
#
# Package identity: <owner>-<repository>-<application_version>-<arch>-<source_sha12>-unsigned.zip
# A source branch name never becomes part of a path; only the resolved SHA does.
#
# Usage:
#   pwsh -File buildscripts/ci/fork/package-windows.ps1 `
#       -SourceDirectory  <repo checkout at source_sha> `
#       -InstallDirectory <install prefix root> `
#       -OutputDirectory  <dir that receives zip + SHA256SUMS.txt + build-manifest.json> `
#       -ProvenancePath   <JSON written by the Windows build helper>
#
#   pwsh -File buildscripts/ci/fork/package-windows.ps1 -ExportResourceExpectations
#       prints the default structural resource expectations as JSON (testability hook).

[CmdletBinding()]
param(
    [string] $SourceDirectory,
    [string] $InstallDirectory,
    [string] $OutputDirectory,
    [string] $ProvenancePath,
    [ValidateSet('x64', 'arm64')]
    [string] $Architecture = 'x64',
    [string[]] $AdditionalResourceExpectation = @(),
    [switch] $ExportResourceExpectations
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$script:IsWindowsHost = ($env:OS -eq 'Windows_NT')

# Identity fields that MUST come from the build helper's provenance file.
# The manifest is not allowed to invent any of these.
$script:ProvenanceRequiredKeys = @(
    'repository'
    'requested_source_ref'
    'source_sha'
    'framework_url'
    'framework_sha'
    'workflow_sha'
    'run_id'
    'run_attempt'
    'application_version'
    'channel'
    'build_type'
    'features'
    'toolchain'
    'dependency_lock'
)

# Relative install-tree paths that every Windows `app` configuration install
# produces. Verified against the real install() rules; see the comment on each
# entry. Fonts and MuseScore's own QML are embedded in the executable via qrc on
# Windows (src/app/CMakeLists.txt installs fonts only on macOS, and
# src/engraving/CMakeLists.txt uses qt_add_big_resources), so there are no
# on-disk font files to assert. MuseScore resources land at the install prefix
# root because MUSE_APP_INSTALL_RESOURCES_LOCATION is "." on Windows.
#
# kind:
#   file     - path must exist as a file
#   anyfile  - at least one of paths must exist as a file
#   dirhas   - path must be a directory containing at least one file (optional filter)
function Get-CoreResourceExpectation {
    return @(
        @{ kind = 'file'; path = 'bin/qt.conf'
            description = 'Qt runtime configuration generated by windeployqt (Qt6CoreDeploySupport GENERATE_QT_CONF)' }
        @{ kind = 'file'; path = 'bin/platforms/qwindows.dll'
            description = 'Qt Windows platform plugin (windeployqt --plugindir bin)' }
        @{ kind = 'file'; path = 'bin/Qt6Core.dll'; description = 'Qt Core runtime' }
        @{ kind = 'file'; path = 'bin/Qt6Gui.dll'; description = 'Qt Gui runtime' }
        @{ kind = 'file'; path = 'bin/Qt6Qml.dll'; description = 'Qt Qml runtime' }
        @{ kind = 'file'; path = 'bin/Qt6Quick.dll'; description = 'Qt Quick runtime' }
        @{ kind = 'file'; path = 'bin/opengl32sw.dll'
            description = 'Qt software rasterizer used by QT_QUICK_BACKEND=software' }
        @{ kind = 'anyfile'; paths = @('bin/vcruntime140.dll', 'bin/msvcp140.dll', 'bin/vcruntime140_1.dll')
            description = 'MSVC native runtime dependency deployed by windeployqt' }
        @{ kind = 'dirhas'; path = 'qml'; filter = 'qmldir'
            description = "Qt QML modules (uiengine.cpp adds <exe>/../qml to the import path)" }
        @{ kind = 'dirhas'; path = 'plugins'
            description = 'MuseScore QML plugins installed at the resources root' }
        @{ kind = 'dirhas'; path = 'extensions'
            description = 'MuseScore extensions installed at the resources root' }
        @{ kind = 'file'; path = 'tables/en-us-symbols.mus'
            description = 'Braille table (src/braille/tables/CMakeLists.txt)' }
        @{ kind = 'file'; path = 'locale/languages.json'
            description = 'Translation index (share/locale/CMakeLists.txt)' }
        @{ kind = 'dirhas'; path = 'locale'; filter = '*.qm'
            description = 'Compiled MuseScore and Qt translations' }
        @{ kind = 'file'; path = 'sound/MS Basic.sf3'
            description = 'Bundled soundfont (share/sound/CMakeLists.txt, MUE_INSTALL_SOUNDFONT)' }
        @{ kind = 'file'; path = 'sound/MS Basic_License.md'
            description = 'Bundled soundfont license notice' }
        @{ kind = 'dirhas'; path = 'licenses/qt-attribution'
            description = 'Qt attribution metadata of the shipped modules (SetupLicenseNotices.cmake, from the installed kit)' }
        @{ kind = 'file'; path = 'licenses/LICENSE.txt'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/SOURCE-REFS.txt'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/qt/GPL-3.0-only.txt'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/qt/LGPL-3.0-only.txt'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/qt/Qt-GPL-exception-1.0.txt'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/fdk-aac/NOTICE'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/asiosdk/LICENSE.txt'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/harfbuzz/COPYING'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/kddockwidgets/LICENSE.txt'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/vst3sdk/base/LICENSE.txt'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/zlib/README'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/libsndfile/COPYING'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/openssl/LICENSE'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/freetype/LICENSE.TXT'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/fluidsynth/LICENSE'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/lame/COPYING'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/flac/COPYING.Xiph'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/opus/COPYING'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/libopusenc/COPYING'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/stb-vorbis/stb_vorbis.c'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/kors/kors_async/LICENSE'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/utf8cpp/LICENSE'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/pugixml/pugixml.hpp'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/picojson/picojson.h'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/liblouis/COPYING.LESSER'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/intervaltree/LICENSE'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/dtl/COPYING'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/beatroot/COPYING'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/rtf2html/COPYING.LESSER'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'licenses/fonts/bravura/OFL.txt'
            description = 'License or notice installed by the source tree (see SetupLicenseNotices.cmake)' }
        @{ kind = 'file'; path = 'styles/MuseJazz.mss'; description = 'Bundled style' }
        @{ kind = 'file'; path = 'templates/My_First_Score.mscx'; description = 'Bundled score template' }
        @{ kind = 'dirhas'; path = 'wallpapers'; filter = '*.png'
            description = 'Bundled wallpapers' }
        @{ kind = 'file'; path = 'workspaces/Default.mws'; description = 'Default workspace' }
        @{ kind = 'file'; path = 'testflowscripts/TC11_CommandPaletteDialog.js'
            description = 'Installed GUI regression test used by the runtime package check' }
        @{ kind = 'file'; path = 'testflowscripts/TC14_CommandPaletteAnnounce.js'
            description = 'Installed GUI regression test used by the runtime package check' }
    )
}

function Fail {
    param([Parameter(Mandatory = $true)][string] $Message)
    throw "package-windows: $Message"
}

function Write-Section {
    param([Parameter(Mandatory = $true)][string] $Message)
    Write-Host "== $Message"
}

function Get-JsonField {
    param(
        [Parameter(Mandatory = $false)] $Object,
        [Parameter(Mandatory = $true)][string] $Name
    )

    if ($null -eq $Object) {
        return $null
    }

    $property = $Object.PSObject.Properties[$Name]
    if ($null -eq $property) {
        return $null
    }

    return $property.Value
}

function Get-Sha256 {
    param([Parameter(Mandatory = $true)][string] $Path)
    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        Fail "cannot hash missing file: $Path"
    }
    return (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()
}

function Resolve-RequiredDirectory {
    param(
        [Parameter(Mandatory = $true)][string] $Path,
        [Parameter(Mandatory = $true)][string] $Name
    )

    if ([string]::IsNullOrWhiteSpace($Path)) {
        Fail "-$Name is required"
    }

    if (-not (Test-Path -LiteralPath $Path -PathType Container)) {
        Fail "-$Name directory not found: $Path"
    }

    return (Resolve-Path -LiteralPath $Path).Path.TrimEnd([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar)
}

function Resolve-FullPath {
    param([Parameter(Mandatory = $true)][string] $Path)
    return [IO.Path]::GetFullPath($Path).TrimEnd([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar)
}

function Test-PathInside {
    param(
        [Parameter(Mandatory = $true)][string] $Parent,
        [Parameter(Mandatory = $true)][string] $Child
    )

    $parentFull = Resolve-FullPath -Path $Parent
    $childFull = Resolve-FullPath -Path $Child
    $separator = [IO.Path]::DirectorySeparatorChar
    return $childFull.StartsWith("$parentFull$separator", [StringComparison]::OrdinalIgnoreCase)
}

function Read-VersionCmake {
    param([Parameter(Mandatory = $true)][string] $Path)

    if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) {
        Fail "version.cmake not found at $Path; -SourceDirectory must be an application checkout"
    }

    $text = Get-Content -LiteralPath $Path -Raw
    $values = @{}
    $names = @(
        'MUSE_APP_NAME_MACHINE_READABLE',
        'MUSE_APP_VERSION_MAJOR',
        'MUSE_APP_VERSION_MINOR',
        'MUSE_APP_VERSION_PATCH',
        'MUSE_APP_UNSTABLE'
    )

    foreach ($name in $names) {
        $pattern = "(?m)^\s*set\(\s*$name\s+""?([^""\)\r\n]+)""?\s*\)"
        $match = [regex]::Match($text, $pattern)
        if (-not $match.Success) {
            Fail "version.cmake does not define $name ($Path)"
        }
        $values[$name] = $match.Groups[1].Value.Trim()
    }

    return $values
}

function Get-ExpectedExecutableRelativePath {
    param([Parameter(Mandatory = $true)][hashtable] $Version)

    $name = $Version['MUSE_APP_NAME_MACHINE_READABLE']
    $major = $Version['MUSE_APP_VERSION_MAJOR']
    if ([string]::IsNullOrWhiteSpace($name) -or [string]::IsNullOrWhiteSpace($major)) {
        Fail 'could not derive the installed executable name from version.cmake'
    }
    return "bin/$name$major.exe"
}

function Get-GitHead {
    param([Parameter(Mandatory = $true)][string] $Directory)

    if (-not (Test-Path -LiteralPath (Join-Path $Directory '.git'))) {
        Fail "-SourceDirectory is not a git checkout (no .git): $Directory"
    }

    $head = & git -C $Directory rev-parse HEAD 2>&1
    if ($LASTEXITCODE -ne 0) {
        Fail "git rev-parse HEAD failed in $Directory (exit $LASTEXITCODE): $head"
    }

    return ($head | Select-Object -First 1).ToString().Trim()
}

function Get-RelativePortablePath {
    param(
        [Parameter(Mandatory = $true)][string] $Root,
        [Parameter(Mandatory = $true)][string] $FullPath
    )

    $relative = [IO.Path]::GetRelativePath($Root, $FullPath)
    return ($relative -replace '\\', '/')
}

function Expand-ResourceExpectation {
    <#
        Verifies one expectation inside $Root and returns the concrete relative
        paths that were verified (so the manifest records real evidence, not an
        abstract rule).
    #>
    param(
        [Parameter(Mandatory = $true)][string] $Root,
        [Parameter(Mandatory = $true)] $Expectation
    )

    $kind = [string] $Expectation['kind']
    $description = [string] $Expectation['description']

    switch ($kind) {
        'file' {
            $relative = [string] $Expectation['path']
            $full = Join-Path $Root ($relative -replace '/', [IO.Path]::DirectorySeparatorChar)
            if (-not (Test-Path -LiteralPath $full -PathType Leaf)) {
                Fail "install tree is missing required file '$relative' ($description)"
            }
            return @($relative)
        }
        'anyfile' {
            foreach ($relative in @($Expectation['paths'])) {
                $full = Join-Path $Root ($relative -replace '/', [IO.Path]::DirectorySeparatorChar)
                if (Test-Path -LiteralPath $full -PathType Leaf) {
                    return @([string] $relative)
                }
            }
            $candidates = (@($Expectation['paths']) -join ', ')
            Fail "install tree is missing every candidate for '$candidates' ($description)"
        }
        'dirhas' {
            $relative = [string] $Expectation['path']
            $full = Join-Path $Root ($relative -replace '/', [IO.Path]::DirectorySeparatorChar)
            if (-not (Test-Path -LiteralPath $full -PathType Container)) {
                Fail "install tree is missing required directory '$relative' ($description)"
            }

            $filter = [string] $Expectation['filter']
            if ([string]::IsNullOrWhiteSpace($filter)) {
                $filter = '*'
            }

            $found = @(Get-ChildItem -LiteralPath $full -Recurse -File -Filter $filter -ErrorAction SilentlyContinue | Sort-Object FullName)
            if ($found.Count -eq 0) {
                Fail "install directory '$relative' contains no '$filter' files ($description)"
            }

            $results = @()
            foreach ($item in $found) {
                $results += (Get-RelativePortablePath -Root $Root -FullPath $item.FullName)
            }
            return $results
        }
        default {
            Fail "unknown resource expectation kind '$kind'"
        }
    }
}

function Assert-ZipEntrySafe {
    param([Parameter(Mandatory = $true)][string] $EntryName)

    $normalized = $EntryName -replace '\\', '/'
    if ([string]::IsNullOrWhiteSpace($normalized)) {
        Fail 'archive contains an empty entry name'
    }
    if ($normalized.StartsWith('/') -or $normalized -match '^[A-Za-z]:') {
        Fail "archive contains an absolute entry path: $EntryName"
    }
    foreach ($segment in $normalized.Split('/')) {
        if ($segment -eq '..') {
            Fail "archive entry escapes the extraction root: $EntryName"
        }
    }
}

function Write-Sha256Sums {
    param(
        [Parameter(Mandatory = $true)][string] $Path,
        [Parameter(Mandatory = $true)][string] $FileName,
        [Parameter(Mandatory = $true)][string] $Sha256
    )

    $content = "$Sha256  $FileName`n"
    [IO.File]::WriteAllText($Path, $content, [Text.UTF8Encoding]::new($false))
}

if ($ExportResourceExpectations) {
    ConvertTo-Json -InputObject @(Get-CoreResourceExpectation) -Depth 8
    exit 0
}

$sourceRoot = Resolve-RequiredDirectory -Path $SourceDirectory -Name 'SourceDirectory'
$installRoot = Resolve-RequiredDirectory -Path $InstallDirectory -Name 'InstallDirectory'

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    Fail '-OutputDirectory is required'
}
$outputRoot = Resolve-FullPath -Path $OutputDirectory
if (Test-PathInside -Parent $installRoot -Child $outputRoot) {
    Fail "-OutputDirectory must not be inside -InstallDirectory ($outputRoot)"
}
if (-not (Test-Path -LiteralPath $outputRoot -PathType Container)) {
    New-Item -ItemType Directory -Path $outputRoot -Force | Out-Null
}

if ([string]::IsNullOrWhiteSpace($ProvenancePath) -or (-not (Test-Path -LiteralPath $ProvenancePath -PathType Leaf))) {
    Fail "-ProvenancePath not found: $ProvenancePath"
}
$provenance = Get-Content -LiteralPath $ProvenancePath -Raw | ConvertFrom-Json
if ($null -eq $provenance) {
    Fail "-ProvenancePath is not valid JSON: $ProvenancePath"
}

$missing = @()
foreach ($key in $script:ProvenanceRequiredKeys) {
    $value = Get-JsonField -Object $provenance -Name $key
    if ($null -eq $value) {
        $missing += $key
        continue
    }
    if ($value -is [string] -and [string]::IsNullOrWhiteSpace($value)) {
        $missing += $key
    }
}
if ($missing.Count -gt 0) {
    Fail "provenance $ProvenancePath is missing required keys: $($missing -join ', ')"
}

$repository = [string] (Get-JsonField -Object $provenance -Name 'repository')
$sourceSha = ([string] (Get-JsonField -Object $provenance -Name 'source_sha')).Trim()
$applicationVersion = ([string] (Get-JsonField -Object $provenance -Name 'application_version')).Trim()
$channel = [string] (Get-JsonField -Object $provenance -Name 'channel')
$buildType = [string] (Get-JsonField -Object $provenance -Name 'build_type')
$provenanceArchitecture = Get-JsonField -Object $provenance -Name 'architecture'

if ($provenanceArchitecture -and ([string] $provenanceArchitecture) -ne $Architecture) {
    Fail "provenance architecture '$provenanceArchitecture' does not match -Architecture '$Architecture'"
}

if ($sourceSha -notmatch '^[0-9a-fA-F]{7,40}$') {
    Fail "provenance source_sha is not a git object id: '$sourceSha'"
}

# Cross-check the source identity against the actual checkout that produced the
# install tree. This is a real check, not manifest self-consistency.
$headSha = Get-GitHead -Directory $sourceRoot
if ($headSha.ToLowerInvariant() -ne $sourceSha.ToLowerInvariant()) {
    Fail "-SourceDirectory HEAD ($headSha) does not match provenance source_sha ($sourceSha)"
}

$version = Read-VersionCmake -Path (Join-Path $sourceRoot 'version.cmake')
$derivedVersion = "$($version['MUSE_APP_VERSION_MAJOR']).$($version['MUSE_APP_VERSION_MINOR']).$($version['MUSE_APP_VERSION_PATCH'])"
if (-not $applicationVersion.StartsWith($derivedVersion, [StringComparison]::Ordinal)) {
    Fail "-SourceDirectory version.cmake is $derivedVersion but provenance application_version is $applicationVersion"
}

$executableRelativePath = Get-ExpectedExecutableRelativePath -Version $version
$executableFullPath = Join-Path $installRoot ($executableRelativePath -replace '/', [IO.Path]::DirectorySeparatorChar)
if (-not (Test-Path -LiteralPath $executableFullPath -PathType Leaf)) {
    Fail ("install tree is missing the application executable '$executableRelativePath' (expected $executableFullPath). " +
          'A metadata-only install directory cannot be packaged.')
}
$executableSize = (Get-Item -LiteralPath $executableFullPath).Length
if ($executableSize -le 0) {
    Fail "application executable is empty: $executableFullPath"
}

Write-Section "Structural validation of $installRoot"
$resourceExpectations = @()
foreach ($expectation in (Get-CoreResourceExpectation)) {
    $verified = Expand-ResourceExpectation -Root $installRoot -Expectation $expectation
    $resourceExpectations += $verified
}
foreach ($extra in $AdditionalResourceExpectation) {
    $extraRelative = ($extra -replace '\\', '/')
    $extraFull = Join-Path $installRoot ($extraRelative -replace '/', [IO.Path]::DirectorySeparatorChar)
    if (-not (Test-Path -LiteralPath $extraFull)) {
        Fail "install tree is missing additional required path '$extraRelative'"
    }
    $resourceExpectations += $extraRelative
}
$resourceExpectations = @($resourceExpectations | Sort-Object -Unique)
Write-Host "verified $($resourceExpectations.Count) resource paths, executable $executableRelativePath ($executableSize bytes)"

# ---------------------------------------------------------------------------
# Archive
# ---------------------------------------------------------------------------
Write-Section 'Creating archive'
$safeRepository = ($repository -replace '[^A-Za-z0-9._-]', '-')
$safeVersion = ($applicationVersion -replace '[^A-Za-z0-9._-]', '-')
$shortSha = $sourceSha.Substring(0, [Math]::Min(12, $sourceSha.Length))
$packageFileName = "$safeRepository-$safeVersion-$Architecture-$shortSha-unsigned.zip"
$packagePath = Join-Path $outputRoot $packageFileName
$sha256SumsPath = Join-Path $outputRoot 'SHA256SUMS.txt'
$manifestPath = Join-Path $outputRoot 'build-manifest.json'

$staleZips = @(Get-ChildItem -LiteralPath $outputRoot -File -Filter '*.zip' -ErrorAction SilentlyContinue |
    Where-Object { $_.FullName -ne $packagePath })
if ($staleZips.Count -gt 0) {
    Fail "refusing to package: -OutputDirectory already contains unexpected zip file(s): $($staleZips.Name -join ', ')"
}

foreach ($stale in @($packagePath, $sha256SumsPath, $manifestPath)) {
    if (Test-Path -LiteralPath $stale) {
        Remove-Item -LiteralPath $stale -Force
    }
}

try {
    [System.IO.Compression.ZipFile]::CreateFromDirectory(
        $installRoot,
        $packagePath,
        [System.IO.Compression.CompressionLevel]::Optimal,
        $false)
} catch {
    if (Test-Path -LiteralPath $packagePath) {
        Remove-Item -LiteralPath $packagePath -Force
    }
    Fail "archive creation failed: $($_.Exception.Message)"
}

if (-not (Test-Path -LiteralPath $packagePath -PathType Leaf)) {
    Fail "archive command reported success but produced no file: $packagePath"
}

# ---------------------------------------------------------------------------
# Archive integrity + extract into a directory containing spaces
# ---------------------------------------------------------------------------
Write-Section 'Verifying archive integrity'
$archive = [System.IO.Compression.ZipFile]::OpenRead($packagePath)
$expectedEntry = ($executableRelativePath -replace '\\', '/')
$entryCount = 0
$foundExecutableEntry = $false
try {
    foreach ($entry in $archive.Entries) {
        Assert-ZipEntrySafe -EntryName $entry.FullName
        if ($entry.FullName -eq '') {
            continue
        }
        $entryCount++
        if (($entry.FullName -replace '\\', '/') -eq $expectedEntry) {
            $foundExecutableEntry = $true
        }
    }
} finally {
    $archive.Dispose()
}
if ($entryCount -eq 0) {
    Fail 'archive contains no entries'
}
if (-not $foundExecutableEntry) {
    Fail "archive does not contain the executable entry '$expectedEntry'"
}

$integrityRoot = Join-Path $outputRoot 'integrity extract with spaces'
if (Test-Path -LiteralPath $integrityRoot) {
    Remove-Item -LiteralPath $integrityRoot -Recurse -Force
}
New-Item -ItemType Directory -Path $integrityRoot -Force | Out-Null
try {
    [System.IO.Compression.ZipFile]::ExtractToDirectory($packagePath, $integrityRoot)
    $extractedExe = Join-Path $integrityRoot ($executableRelativePath -replace '/', [IO.Path]::DirectorySeparatorChar)
    if (-not (Test-Path -LiteralPath $extractedExe -PathType Leaf)) {
        Fail "archive extraction did not reproduce '$executableRelativePath' in a spaced directory"
    }
    if ((Get-Item -LiteralPath $extractedExe).Length -ne $executableSize) {
        Fail 'extracted executable size differs from the installed executable'
    }
} finally {
    if (Test-Path -LiteralPath $integrityRoot) {
        Remove-Item -LiteralPath $integrityRoot -Recurse -Force
    }
}
Write-Host "archive integrity OK: $entryCount entries"

# ---------------------------------------------------------------------------
# Manifest + checksums
# ---------------------------------------------------------------------------
Write-Section 'Writing SHA256SUMS.txt and build-manifest.json'
$packageSize = (Get-Item -LiteralPath $packagePath).Length
$packageSha = Get-Sha256 -Path $packagePath
Write-Sha256Sums -Path $sha256SumsPath -FileName $packageFileName -Sha256 $packageSha

$manifest = [ordered]@{
    manifest_version       = 1
    package_format         = 'zip'
    repository             = $repository
    requested_source_ref   = [string] (Get-JsonField -Object $provenance -Name 'requested_source_ref')
    source_sha             = $sourceSha
    framework_url          = [string] (Get-JsonField -Object $provenance -Name 'framework_url')
    framework_sha          = [string] (Get-JsonField -Object $provenance -Name 'framework_sha')
    workflow_sha           = [string] (Get-JsonField -Object $provenance -Name 'workflow_sha')
    run_id                 = [string] (Get-JsonField -Object $provenance -Name 'run_id')
    run_attempt            = [string] (Get-JsonField -Object $provenance -Name 'run_attempt')
    application_version    = $applicationVersion
    channel                = $channel
    architecture           = $Architecture
    build_type             = $buildType
    features               = Get-JsonField -Object $provenance -Name 'features'
    toolchain              = Get-JsonField -Object $provenance -Name 'toolchain'
    dependency_lock        = Get-JsonField -Object $provenance -Name 'dependency_lock'
    package                = [ordered]@{
        filename = $packageFileName
        size     = $packageSize
        sha256   = $packageSha
    }
    executable             = $executableRelativePath
    resource_expectations  = $resourceExpectations
}
[IO.File]::WriteAllText($manifestPath, (ConvertTo-Json -InputObject $manifest -Depth 10), [Text.UTF8Encoding]::new($false))

# Exactly the expected package must exist: a metadata-only or multi-zip directory
# must not be able to masquerade as a successful artifact.
$zips = @(Get-ChildItem -LiteralPath $outputRoot -File -Filter '*.zip' -ErrorAction SilentlyContinue)
if ($zips.Count -ne 1 -or $zips[0].FullName -ne $packagePath) {
    Fail "expected exactly one package '$packageFileName' in $outputRoot, found: $($zips.Name -join ', ')"
}
if (-not (Test-Path -LiteralPath $sha256SumsPath -PathType Leaf) -or -not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
    Fail 'manifest or checksum file was not produced'
}

Write-Host ''
Write-Host "package:  $packageFileName"
Write-Host "size:     $packageSize bytes"
Write-Host "sha256:   $packageSha"
Write-Host "sha file: SHA256SUMS.txt"
Write-Host "manifest: build-manifest.json"
Write-Host 'package-windows: OK'
